package com.github.nsc.de.shake.lexer

import com.github.nsc.de.shake.lexer.token.TokenType
import com.github.nsc.de.shake.util.characterinput.characterinputstream.CharacterInputStream
import com.github.nsc.de.shake.util.characterinput.characterinputstream.SourceCharacterInputStream
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

class TokenPosition {

    @Test
    @Suppress("deprecation")
    fun testGetBasicPosition() {
        val chars: CharacterInputStream = SourceCharacterInputStream("<tests>", "var test = 10;")
        val lexer = Lexer(chars)
        val `in` = lexer.makeTokens()
        Assertions.assertSame(TokenType.KEYWORD_VAR, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        var start = `in`.map.resolve(`in`.peek().start)
        var end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(0, start.index)
        Assertions.assertSame(1, start.column)
        Assertions.assertSame(1, start.line)
        Assertions.assertSame(2, end.index)
        Assertions.assertSame(3, end.column)
        Assertions.assertSame(1, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.IDENTIFIER, `in`.peek().type)
        Assertions.assertEquals("test", `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(4, start.index)
        Assertions.assertSame(5, start.column)
        Assertions.assertSame(1, start.line)
        Assertions.assertSame(7, end.index)
        Assertions.assertSame(8, end.column)
        Assertions.assertSame(1, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.ASSIGN, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(9, start.index)
        Assertions.assertSame(10, start.column)
        Assertions.assertSame(1, start.line)
        Assertions.assertSame(9, end.index)
        Assertions.assertSame(10, end.column)
        Assertions.assertSame(1, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.INTEGER, `in`.peek().type)
        Assertions.assertEquals("10", `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(11, start.index)
        Assertions.assertSame(12, start.column)
        Assertions.assertSame(1, start.line)
        Assertions.assertSame(12, end.index)
        Assertions.assertSame(13, end.column)
        Assertions.assertSame(1, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.SEMICOLON, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(13, start.index)
        Assertions.assertSame(14, start.column)
        Assertions.assertSame(1, start.line)
        Assertions.assertSame(13, end.index)
        Assertions.assertSame(14, end.column)
        Assertions.assertSame(1, end.line)
    }

    @Test
    @Suppress("deprecation")
    fun testGetMultiLinePosition() {
        val chars: CharacterInputStream = SourceCharacterInputStream("<tests>", "var test\n  = \n10;")
        val lexer = Lexer(chars)
        val `in` = lexer.makeTokens()
        Assertions.assertSame(TokenType.KEYWORD_VAR, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        var start = `in`.map.resolve(`in`.peek().start)
        var end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(0, start.index)
        Assertions.assertSame(1, start.column)
        Assertions.assertSame(1, start.line)
        Assertions.assertSame(2, end.index)
        Assertions.assertSame(3, end.column)
        Assertions.assertSame(1, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.IDENTIFIER, `in`.peek().type)
        Assertions.assertEquals("test", `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(4, start.index)
        Assertions.assertSame(5, start.column)
        Assertions.assertSame(1, start.line)
        Assertions.assertSame(7, end.index)
        Assertions.assertSame(8, end.column)
        Assertions.assertSame(1, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.LINE_SEPARATOR, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(8, start.index)
        Assertions.assertSame(0, start.column)
        Assertions.assertSame(2, start.line)
        Assertions.assertSame(8, end.index)
        Assertions.assertSame(0, end.column)
        Assertions.assertSame(2, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.ASSIGN, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(11, start.index)
        Assertions.assertSame(3, start.column)
        Assertions.assertSame(2, start.line)
        Assertions.assertSame(11, end.index)
        Assertions.assertSame(3, end.column)
        Assertions.assertSame(2, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.LINE_SEPARATOR, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(13, start.index)
        Assertions.assertSame(1, start.column)
        Assertions.assertSame(3, start.line)
        Assertions.assertSame(13, end.index)
        Assertions.assertSame(1, end.column)
        Assertions.assertSame(3, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.INTEGER, `in`.peek().type)
        Assertions.assertEquals("10", `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(14, start.index)
        Assertions.assertSame(2, start.column)
        Assertions.assertSame(3, start.line)
        Assertions.assertSame(15, end.index)
        Assertions.assertSame(3, end.column)
        Assertions.assertSame(3, end.line)
        `in`.skip()
        Assertions.assertSame(TokenType.SEMICOLON, `in`.peek().type)
        Assertions.assertSame(null, `in`.peek().value)
        start = `in`.map.resolve(`in`.peek().start)
        end = `in`.map.resolve(`in`.peek().end)
        Assertions.assertSame(16, start.index)
        Assertions.assertSame(4, start.column)
        Assertions.assertSame(3, start.line)
        Assertions.assertSame(16, end.index)
        Assertions.assertSame(4, end.column)
        Assertions.assertSame(3, end.line)
    }
}